"""Updated tables to show relationships

Revision ID: 09e80e298588
Revises: a734cd507d0f
Create Date: 2026-02-02 16:20:35.406308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e80e298588'
down_revision: Union[str, Sequence[str], None] = 'a734cd507d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('result', sa.Integer(), nullable=False))
    op.add_column('predictions', sa.Column('probability', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'predictions', 'features', ['feature_id'], ['id'])
    op.drop_column('predictions', 'prediction_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('prediction_result', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'probability')
    op.drop_column('predictions', 'result')
    # ### end Alembic commands ###
